In [1]:
import numpy as np

In [2]:
mx_1s=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [3]:
mx_1s=np.ones(5)
print(mx_1s)

[1. 1. 1. 1. 1.]


In [4]:
mx_1s.dtype


dtype('float64')

In [5]:
mx_1s=np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
mx_1s=np.ones((3,4),dtype=int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [7]:
mx_0s=np.zeroes((4,6))
print(mx_0s)

AttributeError: module 'numpy' has no attribute 'zeroes'

In [8]:
mx_0s=np.zeros((4,6))
print(mx_0s)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [9]:
mx_0s=np.zeros((4,6), dtype = bool)
print(mx_0s)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [10]:
mx_0s=np.zeros((4,6), dtype = str)
print(mx_0s)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [11]:
em_str = ''
print(bool(em_str))

False


In [12]:
em_mx=np.empty((3,3))
print(em_mx)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.58095440e-321]
 [8.90111877e-308 4.00540456e-307 1.89145198e-307]]
